project:
  type: website
  render:
    - index.qmd
  resources:
    - cv.html
    - cv_files

website:
  title: "Lukas Burk"
  site-url: https://lukasburk.de
  favicon: profile.jpg
  twitter-card: true
  open-graph:
    locale: en_US
    site-name: Lukas Burk
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.html
        text: CV
  page-footer:
    left: "CC-BY 2023, Lukas Burk"
    center:
      - icon: mastodon
        aria-label: Mastodon
        href: https://norden.social/@jemsu
      - icon: github
        aria-label: GitHub
        href: https://github.com/jemus42
      - icon: envelope
        aria-label: E-Mail
        href: "mailto:hi@lukasburk.de"

format:
  html:
    theme:
      light: [flatly, style-light.scss, style-common.scss]
      dark: [darkly, style-dark.scss, style-common.scss]
    toc: true
    email-obfuscation: references
    smooth-scroll: true
    link-external-newwindow: true
    #license: CC BY

execute:
  freeze: auto
