project:
  type: website
  render:
    # Need to exlude cv.Rmd from quarto rendering
    - index.qmd
    - listing.qmd
    - publications.qmd
    - posts/*
  resources:
    - favicon.ico
    - umami.html
    - cv.html
    - cv_files
    - .well-known
  preview:
    port: 4200
    browser: false

website:
  title: "Lukas Burk"
  # site-url and description needed for RSS feed
  site-url: https://lukasburk.de
  description: "lukasburk.de - A perfectly cromulent website."
  favicon: assets/profile.jpg
  twitter-card: true
  open-graph:
    locale: en_US
    site-name: Lukas Burk
  navbar:
    left:
      - href: publications.qmd
      - href: listing.qmd
    right:
      - href: cv.html
        text: CV
  page-footer:
    left: "CC-BY 2024, Lukas Burk"
    center:
      - icon: github
        aria-label: GitHub
        href: https://github.com/jemus42
      - icon: envelope
        aria-label: E-Mail
        href: "mailto:hi@lukasburk.de"

format:
  html:
    theme:
      light: [flatly, style/light.scss, style/common.scss]
      dark: [darkly, style/dark.scss, style/common.scss]
    toc: true
    email-obfuscation: references
    smooth-scroll: true
    fig-align: center
    link-external-newwindow: true
    link-external-icon: true
    # https://quarto.org/docs/output-formats/html-code.html
    code-tools: false
    code-copy: hover
    code-link: true
    highlight-style: github
    # https://quarto.org/docs/output-formats/html-lightbox-figures.html
    lightbox: true
    html-math-method: katex
    footnotes-hover: true
    # Not sure how to specifcy a CSL file for it to work on netlify
    # csl: nature.csl
    # resource-path:
    #   - "/Users/Lukas/.local/csl"
    include-in-header:
      - assets/umami.html
    comments:
      giscus:
        repo: jemus42/lukasburk.de
        category: Announcements
        mapping: pathname
        reactions-enabled: true
        loading: lazy
        theme:
          light: light
          dark: dark_dimmed
    # Don't like how this is rendered by default, adding license manually in footer
    #license: CC BY

execute:
  freeze: auto
