project:
  type: website
  render:
    # Need to exlude cv.Rmd from quarto rendering
    - index.qmd
    - listing.qmd
    - posts/*
  resources:
    - umami.html
    - cv.html
    - cv_files
    - .well-known

website:
  title: "Lukas Burk"
  # site-url and description needed for RSS feed
  site-url: https://lukasburk.de
  description: "lukasburk.de - A perfectly cromulent website."
  favicon: profile.jpg
  twitter-card: true
  open-graph:
    locale: en_US
    site-name: Lukas Burk
  navbar:
    left:
      - href: listing.qmd
    right:
      - href: cv.html
        text: CV
  page-footer:
    left: "CC-BY 2024, Lukas Burk"
    center:
      - icon: github
        aria-label: GitHub
        href: https://github.com/jemus42
      - icon: envelope
        aria-label: E-Mail
        href: "mailto:hi@lukasburk.de"

format:
  html:
    theme:
      light: [flatly, style-light.scss, style-common.scss]
      dark: [darkly, style-dark.scss, style-common.scss]
    toc: true
    email-obfuscation: references
    smooth-scroll: true
    link-external-newwindow: true
    # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true
    code-copy: hover
    code-link: true
    highlight-style: github
    # https://quarto.org/docs/output-formats/html-lightbox-figures.html
    lightbox: true
    include-in-header:
      - umami.html
    # Don't like how this is rendered by default, adding license manually in footer
    #license: CC BY

execute:
  freeze: auto
