---
title: CV
format:
  awesomecv-typst:
    keep-typ: false
author:
  firstname: Lukas
  lastname: Burk
  position: "PhD Student | Biostatistics & Machine Learning"
  contacts:
    - icon: fa brands github
      text: jemus42
      url: https://github.com/jemus42
    - icon: fa link
      text: lukasburk.de
      url: https://lukasburk.de
date: last-modified
---

# Work Experience

{{< yaml cv/work.yml >}}

# Education

{{< yaml cv/education.yml >}}

# Teaching

{{< yaml cv/teaching.yml >}}

# Skills

{{< yaml cv/skills.yml >}}

# Publications

## Preprints

- J. Piller, L. Orsini, S. Wiegrebe, J. Zobolas, **L. Burk**, S. H. Langbein, P. Studener, M. Goeswein, A. Bender, "Reduction Techniques for Survival Analysis." arXiv, 2025. doi: [2508.05715](https://arxiv.org/abs/2508.05715)
- **L. Burk**, J. Zobolas, B. Bischl, A. Bender, M. N. Wright, and R. Sonabend, "A Large-Scale Neutral Comparison Study of Survival Models on Low-Dimensional Data." arXiv, 2024. doi: [10.48550/arXiv.2406.04098](https://arxiv.org/abs/2406.04098)
- R. Sonabend, J. Zobolas, P. Kopper, **L. Burk**, and A. Bender, "Examining properness in the external validation of survival models with squared and logarithmic losses." arXiv, 2024. doi: [10.48550/arXiv.2212.05260](https://arxiv.org/abs/2212.05260)
- R. Sonabend, F. Pfisterer, A. Mishler, M. Schauer, **L. Burk**, S. Mukherjee, and S. Vollmer, "Flexible Group Fairness Metrics for Survival Analysis." arXiv, 2022. doi: [10.48550/arXiv.2206.03256](https://arxiv.org/abs/2206.03256)

## Journal Articles

- S. Fischer, J. Zobolas, R. Sonabend, et al., "mlr3extralearners: Expanding the mlr3 Ecosystem with Community-Driven Learner Integration." JOSS, vol. 10, no. 115, 2025. doi: [10.21105/joss.08331](https://joss.theoj.org/papers/10.21105/joss.08331)
- **L. Burk**, A. Bender, and M. N. Wright, "High-Dimensional Variable Selection With Competing Events Using Cooperative Penalized Regression." Biometrical Journal, vol. 67, no. 1, 2025. doi: [10.1002/bimj.70036](https://doi.org/10.1002/bimj.70036)
- H. J. Coyle-Asbil, **L. Burk** et al., "Energy expenditure prediction in preschool children: a machine learning approach using accelerometry and external validation." Physiol. Meas., vol. 45, no. 9, 2024. doi: [10.1088/1361-6579/ad7ad2](https://pubmed.ncbi.nlm.nih.gov/39270714/)
- M. Heckmann and **L. Burk**, "Gridsampler – A Simulation Tool to Determine the Required Sample Size for Repertory Grid Studies." JORS, vol. 5, no. 1, 2017. doi: [10.5334/jors.150](https://openresearchsoftware.metajnl.com/articles/10.5334/jors.150)

## Conference Papers

- K. Blesch, N. Koenen, J. Kapar, P. Golchian, **L. Burk**, M. Loecher, M. N. Wright, "Conditional Feature Importance with Generative Modeling Using Adversarial Random Forests." AAAI, vol. 39, no. 15, 2025. doi: [10.1609/aaai.v39i15.33712](https://doi.org/10.1609/aaai.v39i15.33712)

## Contributions to Books

- G. Casalicchio and **L. Burk**, "Evaluation and Benchmarking." in *Applied Machine Learning Using mlr3 in R*, CRC Press, 2024.
- M. N. Wright, **L. Burk**, P. Golchian, J. Kapar, N. Koenen, and S. H. Langbein, "Machine Learning in Epidemiology." in *Handbook of Epidemiology*, Springer, 2024. doi: [10.1007/978-1-4614-6625-3_81-1](https://link.springer.com/rwe/10.1007/978-1-4614-6625-3_81-1)
