---
title: "Publications"
comments: false
---

```{r}
#| eval: false
#| include: false
mybib <- RefManageR::ReadBib("bib.bib", check = FALSE) 
```


::: pub-links

[{{< ai orcid >}}](https://orcid.org/0000-0001-7528-3795)
[{{< ai google-scholar >}}](https://scholar.google.com/citations?user=zcITcLUAAAAJ)
[{{< ai clarivate >}}](https://www.webofscience.com/wos/author/record/ACB-4594-2022)

:::

## Preprints

- **L. Burk**, J. Zobolas, B. Bischl, A. Bender, M. N. Wright, and R. Sonabend, "A Large-Scale Neutral Comparison Study of Survival Models on Low-Dimensional Data." arXiv, Jun. 06, 2024. doi: [10.48550/arXiv.2406.04098](https://arxiv.org/abs/2406.04098).

- R. Sonabend, J. Zobolas, P. Kopper, **L. Burk**, and A. Bender, "Examining properness in the external validation of survival models with squared and logarithmic losses." arXiv, Jun. 03, 2024. doi: [10.48550/arXiv.2212.05260](https://arxiv.org/abs/2212.05260).

## Journal Articles

- **L. Burk**, A. Bender, and M. N. Wright, "High-Dimensional Variable Selection With Competing Events Using Cooperative Penalized Regression", Biometrical Journal, vol. 67, no. 1, p. e70036, 2025, doi: [10.1002/bimj.70036](https://doi.org/10.1002/bimj.70036).

- H. J. Coyle-Asbil, **L. Burk** et al., "Energy expenditure prediction in preschool children: a machine learning approach using accelerometry and external validation" Physiol. Meas., vol. 45, no. 9, p. 095015, Sep. 2024, doi: [10.1088/1361-6579/ad7ad2](https://pubmed.ncbi.nlm.nih.gov/39270714/).

- M. Heckmann and **L. Burk**, "Gridsampler – A Simulation Tool to Determine the Required Sample Size for Repertory Grid Studies." JORS, vol. 5, no. 1, p. 2, Jan. 2017, doi: [10.5334/jors.150](https://openresearchsoftware.metajnl.com/articles/10.5334/jors.150).

## Conference Papers

- Blesch, N. Koenen, J. Kapar, P. Golchian, **L. Burk**, M. Loecher, M. N. Wright, "Conditional Feature Importance with Generative Modeling Using Adversarial Random Forests", Proceedings of the AAAI Conference on Artificial Intelligence, vol. 39, no. 15, Art. no. 15, Apr. 2025, doi: 10.1609/aaai.v39i15.33712.


## Contributions to Books

- G. Casalicchio and **L. Burk**, "Evaluation and Benchmarking." in *Applied machine learning using mlr3 in R
*, 1st ed., B. Bischl, R. Sonabend, L. Kotthoff, and M. Lang, Eds., CRC Press, 2024. Available: <https://mlr3book.mlr-org.com/evaluation_and_benchmarking.html>
